class PagesController < ApplicationController
  # defaults = {title: '[AUTO]', content: 'Autogenerated content'}
  # params = defaults.merge(params)

  before_action :set_page, only: [:show, :edit, :update, :destroy]

  def index
    render json: Page.all
  end

  # NOTE needed?
  def show
    # @page = Page.find(params[:page_id])
    puts '***********************Pages#Show hit'
    render json: @page

    # respond_to do |format|
    #   format.html
    #   format.json {render json: @page}
    # end
  end

  def new
    @story = Story.find(params[:story_id])
    @page = Page.new
  end

  def edit
  end

  def create
    puts '******************************Pages#Create'
    @story = Story.find(params[:story_id])
    # @story = params[:parent_story]
    @page = @story.pages.build(page_params)

    # page = Page.new(page_params)

    # if page.valid?
    if @page.save!
      #  page.save!
       render json: @page, status: 201
       puts 'New page created************************'
    else
       render json: { error: "Error saving page", status: 400 }, status: 400
    end

    # @story = Story.last
    # render json: @story

    # @story = Story.find(params[:story_id])
    # @page = @story.pages.create(page_params)
    # # @page = @story.pages.build(default_params)
    # @page.branches.create(page_params)
    #
    # # @page.branches.build({title: 'boo'})
    #
    # # @page = @story.pages.build()
    #
    # @page.choices.length.times do
    #   @page.branches.build({title: 'boo'})
    #   # @story.pages.build({title: 'boo'})
    #   # @story.save
    # end
    #
    # # render @page
    # @page.save
    # respond_to do |format|
    #   if @page.save
    #     # format.html { redirect_to @page, notice: 'Page was successfully created.' }
    #     # format.json { render :show, status: :created, location: @page }
    #   else
    #     # format.html { render :new }
    #     # format.json { render json: @page.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_page
      @page = Page.find(params[:id])
    end

    def page_params
      # params.fetch(:page, {})
      # permit parent_id
      params.require(:page).permit(:title, :content)
    end

    # def default_params
    #   params = {
    #     title: '[AUTO]',
    #     content: 'Autogenerated'
    #   }
    # end
end
